# Generated by Django 4.0 on 2022-02-27 02:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='UploadImg',
        ),
    ]
